apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlapi
  template:
    metadata:
      labels:
        app: mlapi
    spec:
      containers:
        - name: mlapi
          image: abhinav332/healthcare:2674185615
          imagePullPolicy: Always
          volumeMounts:
          - name: ml-pvc
            mountPath: /ml-pvc
          ports:
            - containerPort: 5000
              protocol: TCP
      volumes:
      - name: ml-pvc
        persistentVolumeClaim:
          claimName: my-longhorn-pvc
