apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlapi
  template:
    metadata:
      labels:
        app: mlapi
    spec:
      containers:
        - name: mlapi
          image: abhinav332/cancer-app:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
