apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: healthcare
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: mlapi
  type: LoadBalancer
