name: Cancer Predcition App CI/CD

env:
  REGISTRY_NAME: abhinav332
  CLUSTER_NAME: healthcare
  CLUSTER_RESOURCE_GROUP: kubeflow-rg
  NAMESPACE: cancerns
  APP_NAME: healthcare

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Job 1
  docker-build:
    if: "contains(github.event.head_commit.message, '[~/docker-build/]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build and Push tagged Docker image
        run: |
          docker build -t ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:${{ github.run_id }} cancer_app/
          docker push ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:${{ github.run_id }}
      - name: Build and Push the latest Docker image
        run: |
          docker build -t ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:latest cancer_app/
          docker push ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:latest
    
  # Job 2  
  kubernetes-build:
    if: "contains(github.event.head_commit.message, '[aks-kubernetes-build]')"
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v1
      - name: install Azure CLI
        run: pip install azure-cli
      - name: configure kubernetes
        run: |
          az login -u abhinav.sharma@studentambassadors.com -p Abhinav@123
          az account set --subscription a9eb49ae-a27a-401b-943d-50913e9e089d
          az aks get-credentials --resource-group kubeflow-rg --name healthcare
      - name: deploy App
        run: | 
          kubectl apply -k k8s/
          kubectl set image deployment ml-deployment mlapi=${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:${{ github.run_id }} -n $NAMESPACE        
