name: Cancer Predcition App CI/CD

env:
  REGISTRY_NAME: abhinav332
  CLUSTER_NAME: healthcare
  CLUSTER_RESOURCE_GROUP: kubeflow-rg
  NAMESPACE: healthcare
  APP_NAME: healthcare
  SECRET: regcred

on:
  push:
    branches:
      - 'master'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the tagged Docker image
        run: docker build -t ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:${{ github.run_id }} cancer_app/
      - name: Push the tagged Docker image
        run: docker push ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:${{ github.run_id }}
      - name: Build the latest Docker image
        run: docker build -t ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:latest cancer_app/
      - name: Push the latest Docker image
        run: docker push ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME }}:latest
      - name: install Azure CLI
        run: pip install azure-cli
      - name: configure kubernetes
        run: |
          az login -u abhinav.sharma@studentambassadors.com -p Abhinav@123
          az account set --subscription a9eb49ae-a27a-401b-943d-50913e9e089d
          az aks get-credentials --resource-group kubeflow-rg --name healthcare
      - name: check installation
        run: kubectl get nodes
