name: Cancer Predcition App CI/CD

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag abhinav332/cancer-app:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push abhinav332/cancer-app:${{steps.vars.outputs.tag}}
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag abhinav332/cancer-app:latest
      - name: Push the latest Docker image
        run: docker push abhinav332/cancer-app:latest
