name: Cancer Predcition App CI/CD

env:
  REGISTRY_NAME: abhinav332
  CLUSTER_NAME: healthcare
  CLUSTER_RESOURCE_GROUP: kubeflow-rg
  NAMESPACE: healthcare
  APP_NAME: healthcare
  SECRET: regcred

on:
  push:
    branches:
      - 'master'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: install Azure CLI
        run: pip install azure-cli
      - name: configure kubernetes
        run: |
          az login -u abhinav.sharma@studentambassadors.com -p Abhinav@123
          az account set --subscription a9eb49ae-a27a-401b-943d-50913e9e089d
          az aks get-credentials --resource-group kubeflow-rg --name healthcare
      - name: deploy App
        run: | 
          kubectl apply -k k8s/
          kubectl set image deployment ml-deployment mlapi=abhinav332/cancer-app:v6 -n $NAMESPACE        
